version: 1
runners:
  Machine:
    config-id: 2
images:
  HelloMachine:
    image: ubuntu
    registry: https://hub.docker.com/repositories/ananteasytocheck
    auth:
      username: ananteasytocheck
      password: Anant@123456123
jobs:
  Deploy_Client_Functions:
    steps:
      - "apt-get update \r"
      - "apt-get -y install openjdk-17-jdk curl\r"
      - "curl -fsSL https://deb.nodesource.com/setup_18.x | bash - \r"
      - "apt-get install -y nodejs\r"
      - "apt-get update && \\\r"
      - "apt-get install -y software-properties-common wget curl && \\\r"
      - "add-apt-repository ppa:deadsnakes/ppa && \\\r"
      - "apt-get update && \\\r"
      - "apt-get install -y python3.9 python3.9-distutils && \\\r"
      - "wget https://bootstrap.pypa.io/get-pip.py && \\ \r"
      - "python3.9 get-pip.py && \\\r"
      - "rm get-pip.py\r"
      - "npm i -g zcatalyst-cli\r"
      - "catalyst -v\r"
      - "cd functions/Node\r"
      - "npm install\r"
      - "cd ../..\r"
      - catalyst deploy --project 33398000000011049 --org 902772821 --token m_1004.9522c305f79622d5ee9028994efe6d09.ffc9e885ba03fed366652137e2b1c60a
stages:
  - name: build
    image: HelloMachine
    jobs:
      - Deploy_Client_Functions